2023-02-02 05:45:28,993 INFO    MainThread:12380 [wandb_setup.py:_flush():75] Loading settings from C:\Users\bhata\.config\wandb\settings
2023-02-02 05:45:28,993 INFO    MainThread:12380 [wandb_setup.py:_flush():75] Loading settings from C:\aiornot\notebooks\wandb\settings
2023-02-02 05:45:28,994 INFO    MainThread:12380 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2023-02-02 05:45:28,994 INFO    MainThread:12380 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-02 05:45:28,994 INFO    MainThread:12380 [wandb_init.py:_log_setup():386] Logging user logs to C:\aiornot\notebooks\wandb\run-20230202_054528-18ocv89x\logs\debug.log
2023-02-02 05:45:28,994 INFO    MainThread:12380 [wandb_init.py:_log_setup():387] Logging internal logs to C:\aiornot\notebooks\wandb\run-20230202_054528-18ocv89x\logs\debug-internal.log
2023-02-02 05:45:28,994 INFO    MainThread:12380 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000029CDAB42D00>
2023-02-02 05:45:28,994 INFO    MainThread:12380 [wandb_init.py:init():420] calling init triggers
2023-02-02 05:45:28,995 INFO    MainThread:12380 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2023-02-02 05:45:28,995 INFO    MainThread:12380 [wandb_init.py:init():471] starting backend
2023-02-02 05:45:28,995 INFO    MainThread:12380 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2023-02-02 05:45:28,998 INFO    MainThread:12380 [backend.py:ensure_launched():219] starting backend process...
2023-02-02 05:45:29,069 INFO    MainThread:12380 [backend.py:ensure_launched():224] started backend process with pid: 17216
2023-02-02 05:45:29,069 INFO    MainThread:12380 [wandb_init.py:init():480] backend started and connected
2023-02-02 05:45:29,083 INFO    MainThread:12380 [wandb_run.py:_label_probe_notebook():921] probe notebook
2023-02-02 05:45:29,085 INFO    MainThread:12380 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-02-02 05:45:29,085 INFO    MainThread:12380 [wandb_init.py:init():550] updated telemetry
2023-02-02 05:45:29,130 INFO    MainThread:12380 [wandb_init.py:init():581] communicating current version
2023-02-02 05:45:30,399 INFO    MainThread:12380 [wandb_init.py:init():586] got version response upgrade_message: "wandb version 0.13.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-02-02 05:45:30,400 INFO    MainThread:12380 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2023-02-02 05:45:30,906 INFO    MainThread:12380 [wandb_init.py:init():624] starting run threads in backend
2023-02-02 05:45:35,988 INFO    MainThread:12380 [wandb_run.py:_console_start():1827] atexit reg
2023-02-02 05:45:35,989 INFO    MainThread:12380 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2023-02-02 05:45:35,989 INFO    MainThread:12380 [wandb_run.py:_redirect():1738] Wrapping output streams.
2023-02-02 05:45:35,991 INFO    MainThread:12380 [wandb_run.py:_redirect():1762] Redirects installed.
2023-02-02 05:45:35,991 INFO    MainThread:12380 [wandb_init.py:init():651] run started, returning control to user process
2023-02-02 05:45:49,906 INFO    MainThread:12380 [wandb_init.py:_pause_backend():299] pausing backend
2023-02-02 05:45:49,906 INFO    MainThread:12380 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2023-02-02 05:47:44,116 INFO    MainThread:12380 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2023-02-02 05:47:44,118 INFO    MainThread:12380 [wandb_run.py:_restore():1769] restore
2023-02-02 05:47:44,395 INFO    MainThread:12380 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 876
  total_bytes: 876
}

2023-02-02 05:47:44,758 INFO    MainThread:12380 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 876
  total_bytes: 876
}

2023-02-02 05:47:44,872 INFO    MainThread:12380 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 876
  total_bytes: 10712
}

2023-02-02 05:47:44,980 INFO    MainThread:12380 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 876
  total_bytes: 10712
}

2023-02-02 05:47:45,089 INFO    MainThread:12380 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 876
  total_bytes: 10712
}

2023-02-02 05:47:45,198 INFO    MainThread:12380 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 876
  total_bytes: 10712
}

2023-02-02 05:47:45,308 INFO    MainThread:12380 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10598
  total_bytes: 10712
}

2023-02-02 05:47:45,416 INFO    MainThread:12380 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10712
  total_bytes: 10712
}

2023-02-02 05:47:45,527 INFO    MainThread:12380 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10712
  total_bytes: 10712
}

2023-02-02 05:47:45,636 INFO    MainThread:12380 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10712
  total_bytes: 10712
}

2023-02-02 05:47:45,745 INFO    MainThread:12380 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10712
  total_bytes: 10712
}

2023-02-02 05:47:45,854 INFO    MainThread:12380 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10712
  total_bytes: 10712
}

2023-02-02 05:47:45,963 INFO    MainThread:12380 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10712
  total_bytes: 10712
}

